### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by tjmonsi** [firebase/polymerfire#346]
Todo:

Review and test the whole polymerfire for Polymer 2 and Polymer 3

- [ ] create a repo for polymerfire using Polymer 2 while reviewing the firestore branch
  - [ ] create use cases for firebase-auth taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.auth
  - [ ] create use cases for firebase-query taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.database
  - [ ] create use cases for firebase-document taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.database
  - [ ] create use cases for firestore taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.firestore

- [ ] create a branch for Polymer 3

- [ ] create a repo for polymerfire using Polymer 3
  - [ ] create use cases for firebase-auth taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.auth
  - [ ] create use cases for firebase-query taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.database
  - [ ] create use cases for firebase-document taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.database
  - [ ] create use cases for firestore taking note of all functionalities involved in https://firebase.google.com/docs/reference/js/firebase.firestore

**Comment by creativeautomaton** [comment]
@tjmonsi  working on a version of of polymerfire for polmer 3 as well you can **npm i polymerfire3** to check it out. right now i need to convert the beaviors to match polymer 3 syntax but i used the modulizer to convert the files to imports and also created the npm to allow install of the package. if you want i can add you as a contributor as this is my first npm package and help is always welcome.
